# Generated by Django 4.2.7 on 2026-06-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='contact@asmitalok.com', max_length=254)),
                ('phone', models.CharField(default='+91 1234567890', max_length=50)),
                ('location', models.CharField(default='India', max_length=200)),
                ('cta_heading', models.CharField(default="Let's Connect", max_length=200)),
                ('cta_subtitle', models.CharField(default='Have a project in mind or want to discuss opportunities?', max_length=300)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('meeting_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('type', models.CharField(default='Full-time', max_length=100)),
                ('responsibilities', models.TextField(help_text='JSON list or newline-separated responsibilities/achievements')),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated technologies used', max_length=500)),
                ('display_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Asmit Alok', max_length=200)),
                ('role', models.CharField(default='Full Stack Developer', max_length=200)),
                ('main_headline', models.CharField(default='Full Stack Developer', max_length=300)),
                ('subtitle', models.TextField(default='Specializing in Angular, ReactJS, Python and Django | Crafting Scalable Web Apps with a User-Centric Approach')),
                ('availability_badge', models.CharField(default='Available for work', max_length=100)),
                ('cta_labels', models.CharField(default="Let's Connect, Resume", max_length=200)),
                ('cta_links', models.CharField(default='#contact, /resume.pdf', max_length=200)),
                ('profile_image', models.CharField(default='/image.jpg', max_length=500)),
                ('resume_link', models.CharField(default='/resume.pdf', max_length=500)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('tech_badges', models.CharField(default='Angular, React, Python, Django', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Asmit Alok', max_length=200)),
                ('email', models.EmailField(default='contact@asmitalok.com', max_length=254)),
                ('phone', models.CharField(default='+91 1234567890', max_length=50)),
                ('location', models.CharField(default='India', max_length=200)),
                ('short_bio', models.TextField(default='Passionate Full Stack Developer specializing in Angular, ReactJS, Python and Django.')),
                ('long_bio', models.TextField(default="I'm a passionate technology enthusiast dedicated to staying at the forefront of emerging industry trends and advancements. My commitment to continuous learning drives me to actively seek opportunities where I can contribute meaningfully to the ever-evolving world of technology.")),
                ('current_role', models.CharField(default='Full Stack Developer', max_length=200)),
                ('current_status', models.CharField(default='Active', max_length=200)),
                ('social_profiles', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=80)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='features_list',
            field=models.TextField(blank=True, help_text='JSON list or newline-separated features', null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='status',
            field=models.CharField(default='Completed', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='last_updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='version_name',
            field=models.CharField(default='v1.0', max_length=100),
        ),
    ]
