# Generated by Django 4.2.7 on 2026-07-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0002_contactsection_experience_herosection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herosection",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="hero/"),
        ),
        migrations.AlterField(
            model_name="projectinfo",
            name="image_url",
            field=models.ImageField(blank=True, null=True, upload_to="projects/"),
        ),
    ]
