# Generated by Django 4.2.7 on 2026-07-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0003_alter_herosection_profile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactsection",
            name="email",
            field=models.EmailField(default="alokasmit@gmail.com", max_length=254),
        ),
        migrations.AlterField(
            model_name="contactsection",
            name="location",
            field=models.CharField(default="Gurugram, India", max_length=200),
        ),
        migrations.AlterField(
            model_name="contactsection",
            name="phone",
            field=models.CharField(default="+91 8210632703", max_length=50),
        ),
        migrations.AlterField(
            model_name="personalprofile",
            name="email",
            field=models.EmailField(default="alokasmit@gmail.com", max_length=254),
        ),
        migrations.AlterField(
            model_name="personalprofile",
            name="location",
            field=models.CharField(default="Gurugram, India", max_length=200),
        ),
        migrations.AlterField(
            model_name="personalprofile",
            name="phone",
            field=models.CharField(default="+91 8210632703", max_length=50),
        ),
    ]
