# Generated by Django 4.2.7 on 2026-07-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0004_alter_contactsection_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herosection",
            name="profile_image",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="personalprofile",
            name="short_bio",
            field=models.TextField(
                default="Passionate Full Stack Developer specializing in Angular, ReactJS, Python and Django with expertise in GenAI and AI integration."
            ),
        ),
    ]
