# Generated by Django 4.2.7 on 2026-07-27 10:35

import ai_assistant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0005_alter_herosection_profile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="file",
            field=models.FileField(
                storage=ai_assistant.models.select_pdf_storage, upload_to="resumes/"
            ),
        ),
    ]
