# Generated by Django 4.2.7 on 2026-07-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0006_alter_resume_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("issuer", models.CharField(max_length=200)),
                ("date_issued", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "image_url",
                    models.ImageField(blank=True, null=True, upload_to="certificates/"),
                ),
                ("credential_url", models.URLField(blank=True, null=True)),
                ("display_order", models.IntegerField(default=0)),
                ("is_featured", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
